use command

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,8 +46,12 @@ jobs:
           echo $env:PATH
         shell: pwsh
       - name: Build
-        run: ./.ci/windows-msvc/build.sh
-        shell: pwsh
+        run: |
+          mkdir build && cd build
+          cmake .. -G "Visual Studio 17 2022" -A x64 -DCITRA_USE_BUNDLED_QT=1 -DCITRA_USE_BUNDLED_SDL2=1 -DCITRA_ENABLE_COMPATIBILITY_REPORTING=OFF -DUSE_DISCORD_PRESENCE=OFF -DENABLE_MF=ON -DENABLE_FFMPEG_VIDEO_DUMPER=ON
+          cd ..
+          msbuild build/citra.sln -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64
+          ctest -VV -C Release || echo "::error ::Test error occurred on Windows MSVC build"
   transifex:
     runs-on: ubuntu-latest
     container: citraemu/build-environments:linux-transifex
